// ─────────────────────────────────────────────────────────────────────────────
// TERMS OF SERVICE — src/pages/TermsPage.jsx
// Route: /terms
//
// IMPORTANT: This is a starting template, not legal advice. Have an actual
// attorney review this before relying on it — especially the SMS/TCPA language
// and the "not financial advice" disclaimers, since AlertGods sends paid trade
// alerts and recurring text messages. Update LAST_UPDATED whenever you edit it.
// ─────────────────────────────────────────────────────────────────────────────

const LAST_UPDATED = "September 22, 2026";
const CONTACT_EMAIL = "support@alertgods.com"; // ← update once your inbox is live
const COMPANY_NAME = "AlertGods";

function Section({ title, children }) {
  return (
    <div style={{ marginBottom: 28 }}>
      <h2 style={{ fontFamily: "'Syne',sans-serif", fontSize: 18, fontWeight: 800, color: "#e8f0f8", marginBottom: 10 }}>
        {title}
      </h2>
      <div style={{ fontSize: 14, color: "#7a9aba", lineHeight: 1.8 }}>{children}</div>
    </div>
  );
}

export default function TermsPage({ onNavigate = () => {} }) {
  const mono = "'JetBrains Mono','Fira Code',monospace";

  return (
    <div style={{ fontFamily: "'DM Sans','Segoe UI',sans-serif", background: "#050c18", color: "#c8d8e8", minHeight: "100vh" }}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600&family=JetBrains+Mono:wght@400;500;600&family=Syne:wght@700;800&display=swap');
        * { box-sizing: border-box; } a { color: #4a8adf; }`}</style>

      <nav style={{ padding: "0 40px", height: 60, display: "flex", alignItems: "center", justifyContent: "space-between", borderBottom: "1px solid #0a1828" }}>
        <button onClick={() => onNavigate("/")} style={{ background: "none", border: "none", cursor: "pointer" }}>
          <span style={{ fontFamily: mono, color: "#00c97a", fontSize: 14, fontWeight: 600, letterSpacing: "0.1em" }}>◈ SIGNALOS</span>
        </button>
        <a href="#/" style={{ fontSize: 13, color: "#4a8adf", textDecoration: "none" }}>← Back home</a>
      </nav>

      <div style={{ maxWidth: 760, margin: "0 auto", padding: "60px 40px 100px" }}>
        <div style={{ fontFamily: mono, fontSize: 10, color: "#4a8adf", letterSpacing: "0.2em", marginBottom: 10 }}>LEGAL</div>
        <h1 style={{ fontFamily: "'Syne',sans-serif", fontSize: "clamp(28px,4vw,36px)", fontWeight: 800, color: "#e8f0f8", marginBottom: 8 }}>
          Terms of Service
        </h1>
        <p style={{ fontSize: 13, color: "#3a5a7a", marginBottom: 40 }}>Last updated: {LAST_UPDATED}</p>

        <Section title="1. What this is">
          {COMPANY_NAME} provides trade alert content — options and futures signals generated by an AI model reviewing live market
          data, delivered via Discord and, for Pro subscribers, SMS. This service is educational and informational only.
        </Section>

        <Section title="2. Not financial advice">
          Nothing {COMPANY_NAME} sends — signals, strategy names, entries, stops, targets, confidence scores, education content, or
          anything said in Discord — is financial, investment, or trading advice, and none of it is personalized to your financial
          situation. {COMPANY_NAME} is not a registered investment adviser or broker-dealer. Trading options and futures involves
          substantial risk of loss and is not suitable for everyone. Past performance of any signal or strategy is not indicative of
          future results. You are solely responsible for your own trading decisions, and you should consult a licensed financial
          advisor before acting on anything sent through this service.
        </Section>

        <Section title="3. Accounts and plans">
          The Free plan is provided at no cost and may be changed or discontinued at any time. The Pro plan is a paid monthly
          subscription billed through Stripe. By subscribing to Pro you authorize recurring monthly charges to your payment method
          until you cancel. You can cancel anytime; you'll keep Pro access through the end of the billing period you already paid
          for, and we don't issue refunds for partial or already-used months.
        </Section>

        <Section title="4. SMS alerts">
          If you provide a phone number and opt in, Pro subscribers may receive automated recurring text messages containing trade
          alerts. Message and data rates may apply. Message frequency varies with market activity. You can opt out at any time by
          replying STOP to any message, which will stop future SMS delivery (it does not cancel your Pro subscription — do that from
          your account or by contacting us). For help, reply HELP or email {CONTACT_EMAIL}.
        </Section>

        <Section title="5. Discord community">
          Access to our Discord server is a benefit of both plans and is governed by Discord's own Terms of Service in addition to
          our server rules. We may remove access for abusive behavior, sharing paid content outside the server, or violating
          Discord's terms, without a refund of any unused subscription time.
        </Section>

        <Section title="6. Acceptable use">
          You agree not to redistribute, resell, or publicly republish signals or content from this service without permission, and
          not to use automated tools to scrape or bulk-extract signal data from the dashboard or Discord.
        </Section>

        <Section title="7. Disclaimer and limitation of liability">
          The service is provided "as is" without warranties of any kind. {COMPANY_NAME} is not liable for any trading losses,
          missed signals, delayed delivery, or downtime, including losses connected to signals generated in error or delivered late.
          To the fullest extent permitted by law, {COMPANY_NAME}'s total liability for any claim relating to the service is limited
          to the amount you paid in the month the claim arose.
        </Section>

        <Section title="8. Changes to these terms">
          We may update these terms from time to time; the "Last updated" date above will reflect the most recent change. Continued
          use of the service after an update means you accept the revised terms.
        </Section>

        <Section title="9. Contact">
          Questions about these terms? Email {CONTACT_EMAIL} or visit our{" "}
          <a href="#/contact">Contact page</a>.
        </Section>
      </div>
    </div>
  );
}
